version: '3.4'

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    networks:
      - net-1
    environment:
      POSTGRES_USER: smoadmin
      POSTGRES_PASSWORD: smopass
#      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ${DATA_DIR}/postgres/databases:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0.1
    networks:
      - net-1
    environment:
      KEYCLOAK_ADMIN: smoadmin
      KEYCLOAK_ADMIN_PASSWORD: smopass
      PROXY_ADDRESS_FORWARDING: true  #important for reverse proxy
    command:
      - start-dev
    ports:
      - 9010:8080

  nginx:
    container_name: nginx
    image: nginx:1.23-alpine
    networks:
      - net-1
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${DATA_DIR}/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ${DATA_DIR}/nginx/conf.d:/etc/nginx/conf.d
      - ${DATA_DIR}/nginx/ssl:/etc/ssl
#      - ${DATA_DIR}/certbot/conf:/etc/letsencrypt
#      - ${DATA_DIR}/certbot/www:/var/www/certbot

#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ${DATA_DIR}/certbot/conf:/etc/letsencrypt
#      - ${DATA_DIR}/certbot/www:/var/www/certbot

  orientdb:
    container_name: orientdb
    build:
      context: ../build/orientdb
      dockerfile: Dockerfile
    user: docker
    ports:
      - 8182:8182 # Gremlin server
      - 2480:2480 # OrientDb http
      - 2424:2424 # OrientDb binary
    networks:
      - net-1
    command: ["server.sh"]
    environment:
      ORIENTDB_OPTS_MEMORY: "-Xms2G -Xmx2G"
    volumes:
      - ${DATA_DIR}/orientdb/databases/:/orientdb/databases
      - ${DATA_DIR}/orientdb/backup/:/orientdb/backup
      - ${DATA_DIR}/orientdb/config/:/orientdb/config

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 1883:1883
      - 5672:5672
      - 15672:15672
      - 15675:15675
    volumes:
      - ${DATA_DIR}/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ${DATA_DIR}/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  app-server:
    container_name: app-server
    image: naskomit/smo-reform:0.1.1
    ports:
      - 9005:9000
    networks:
      - net-1
    volumes:
      - ${DATA_DIR}/import:/data/import



networks:
  net-1:

