---
- name: Deploy docker compose stack
  hosts: vagrant

  tasks:
    - name: Configure variables
      include_tasks: 
        file: 10_configure_variables.yaml

    - name: Deploy stack
      import_role: 
        name: reform-stack-deploy
      become: yes
      become_user: "{{ rf_stack.os.username }}"
