- name: Setup authentication
  hosts: localhost

  tasks:
    - name: Configure variables
      include_tasks: 
        file: 10_configure_variables.yaml
    
    - name: Setup keycloak realm
      community.general.keycloak_realm:
        auth_client_id: admin-cli
        auth_keycloak_url: http://keycloak.local
        auth_realm: master
        auth_username: "{{ rf_stack.keycloak.admin.username }}"
        auth_password: "{{ rf_stack.keycloak.admin.password }}"
        id: reform
        state: present
