- name: Setup authentication
  vars_files:
    - config/reform.yaml
  hosts: localhost

  tasks:
    - name: Setup keycloak realm
      community.general.keycloak_realm:
        auth_client_id: admin-cli
        auth_keycloak_url: https://localhost/auth
        auth_realm: master
        auth_username: "{{ docker_stack.keycloak.admin.user }}"
        auth_password: "{{ docker_stack.keycloak.admin.password }}"
        id: reform
        state: present
