version: '3.4'

services:
  orientdb:
    container_name: orientdb
    build:
      context: build/orientdb
      dockerfile: Dockerfile
    user: docker
    ports:
      - 8182:8182 # Gremlin server
      - 2480:2480 # OrientDb http
      - 2424:2424 # OrientDb binary
    environment:
      - ORIENTDB_OPTS_MEMORY=-Xms2G -Xmx2G
#    command: ["/bin/bash", "-c", "sleep infinity"]
    command: ["server.sh"]
    volumes:
      - ../data/orientdb/databases/:/orientdb/databases
      - ../data/orientdb/backup/:/orientdb/backup
      - ../data/orientdb/config/:/orientdb/config
