version: '3.4'

services:
  orientdb:
    container_name: orientdb
    build:
      context: build/orientdb
      dockerfile: Dockerfile
    user: docker
    ports:
      - 8182:8182 # Gremlin server
      - 2480:2480 # OrientDb http
      - 2424:2424 # OrientDb binary
    networks:
      - net-1
    environment:
      - ORIENTDB_OPTS_MEMORY=-Xms2G -Xmx2G
#    command: ["/bin/bash", "-c", "sleep infinity"]
    command: ["server.sh"]
    volumes:
      - ../data/orientdb/databases/:/orientdb/databases
      - ../data/orientdb/backup/:/orientdb/backup
      - ../data/orientdb/config/:/orientdb/config

  app-server:
    container_name: app-server
    image: demo1_backend:0.1.1
    ports:
      - 9005:9000
    networks:
      - net-1

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0.1
    networks:
      - net-1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
    ports:
      - 9010:8080


networks:
  net-1:

