version: '3.4'

services:
  orientdb:
    container_name: orientdb
    build:
      context: ../build/orientdb
      dockerfile: Dockerfile
    user: docker
    ports:
      - 8182:8182 # Gremlin server
      - 2480:2480 # OrientDb http
      - 2424:2424 # OrientDb binary
    networks:
      - net-1
#    environment:
#      - ORIENTDB_OPTS_MEMORY=-Xms2G -Xmx2G
    command: ["server.sh"]
    environment:
      DATA_DIR: "../../data"
    volumes:
      - ${DATA_DIR}/orientdb/databases/:/orientdb/databases
      - ${DATA_DIR}/orientdb/backup/:/orientdb/backup
      - ${DATA_DIR}/orientdb/config/:/orientdb/config

#  keycloak:
#    container_name: keycloak
#    image: quay.io/keycloak/keycloak:20.0.1
#    networks:
#      - net-1
#    environment:
#      - KEYCLOAK_ADMIN=admin
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#    command:
#      - start-dev
#    ports:
#      - 9010:8080
#
  app-server:
    container_name: app-server
    image: naskomit/smo-reform:0.1.1
    ports:
      - 9005:9000
    networks:
      - net-1
    volumes:
      - ${DATA_DIR}/import:/data/import



networks:
  net-1:

