package sysmo.demo1

import japgolly.scalajs.react.vdom.html_<^._
import sysmo.reform.app.Panel

object InventoryProjectInfoPanel extends Panel {

  import japgolly.scalajs.react._

  case class Props()
  case class State()

  final class Backend($: BackendScope[Props, State]) {
    def render(p: Props, s: State): VdomElement = {
      <.div(
        <.div(^.cls:= "page-title",
          <.h1("Virtual Anatomy Collection")
        ),
        <.div(^.cls:="row",
          <.div(^.cls:= "col-md-6 col-md-offset-2", ^.fontSize:= 1.2.rem,
            <.div(^.cls:= "wrapper wrapper-white",
              <.div(^.marginTop:= 10.px,
                """
                  |Virtual Anatomy Collection includes anonymized DICOM series acquired by computed tomography of the head
                  |and 3D images of skulls generated by micro-computed tomography and laser scanning."""
                  .stripMargin),
              <.div(^.marginTop:= 10.px,
                """
                  |The images stored in the Virtual Anatomy Collection can be used only for scientific purposes."""
                  .stripMargin),

              <.div(^.marginTop:= 10.px,
                """
                  |The organization of the Virtual Anatomy Collection is supported by the Bulgarian National Science Fund
                  |[Grant number ДН11/9 – 15.12.2017; “Investigation of human anatomic variations on three-dimensional models
                  |using innovative and interdisciplinary approaches and organization of a Virtual Anatomy Collection”]"""
                  .stripMargin)

            )
          )
        )
      )
    }
  }

  val component = ScalaComponent.builder[Props]("InventoryProjectInfoPanel")
    .initialState(State())
    .renderBackend[Backend]
//    .componentDidMount{f =>
//      f.props.mt.map(f.props.initialization){ rt =>
//        f.modState(s => s.copy(runtime = ))
//
//      })
//    }
    .build


  def apply(): Unmounted = {
    component(Props())
  }
//    val controllerF = MicroController.initializer1()
//
//    component(new Props {
//      type F[+X] = MicroController.initializer1.F[X]
//      val mt = MicroController.initializer1.runtime.mt
//      val initialization = controllerF
//    })
//  }
}